### ISSUE TITLE
-g 1 flag does not work

### ISSUE THREAD

**Issue by Chenghui123** [tudelft3d/CityGML2OBJs#12]
When I  call the flag ```-g 1```, the output file with the name followed by "Other", and the objects isn't been named as an integer from 1 to n.
So, what's wrong with my work?
Thanks for your help.

**Comment by fbiljecki** [comment]
Can you share the file so I can reproduce  the issue?

**Comment by Chenghui123** [comment]
[Hammarby.zip](https://github.com/tudelft3d/CityGML2OBJs/files/2551952/Hammarby.zip)
Thank you very much!

**Comment by fbiljecki** [comment]
The buildings in the file are stored as GenericCityObject, not as Building, with denoted semantic surfaces. Since the objects are not semantically labelled, the result you get is as expected. If you need that, consider procuring a semantically rich model.

**Comment by Chenghui123** [comment]
OK, thanks!
